### ISSUE TITLE
Base64 version

### ISSUE THREAD

**Issue by AverageMarcus** [danielthepope/imojify#9]
It'd be nice to not need to have all the image files. I'd like to see a CSS file with all the images included in as base64 encoded string. 

This should be in addition the the existing as it'd be very bad for someone who only uses one or two emojis to have to download ALL of them.

**Comment by danielthepope** [comment]
I tried that first, it was 5MB :scream:

**Comment by AverageMarcus** [comment]
But on an emoji-heavy site (chat) it could reduce the network connections

**Comment by AverageMarcus** [comment]
Though I guess caching would solve that pretty quick

**Comment by danielthepope** [comment]
I think if I did a server-side version of this, you could have Base 64 CSS file, then process it with something like uncss to dramatically reduce the size of the file.

**Comment by AverageMarcus** [comment]
What do you mean by server-side version?

**Comment by danielthepope** [comment]
So let's say you have a Jekyll blog and you have all of your posts in markdown with :emoji: written in there. At some point that's got to be compiled to HTML before the client sees it. So at the Jekyll build step if it could convert :emoji: to `<span>`-oji so that `gemojify()` doesn't need to be run on the client, we could use something like uncss to remove any classes that aren't being used.

...except Jekyll runs in Ruby, not Node.

... and I haven't thought this through at all :stuck_out_tongue:

**Comment by AverageMarcus** [comment]
I'm going to close this issue and think about it more.

**Comment by AverageMarcus** [comment]
On a related note, you should have totally called this spanoji
